export const activityFormConfig = [
  {
    label: 'Title',
    name: 'title',
    type: 'text',
    validation: { required: true },
  },
  {
    label: 'Status',
    name: 'activity_status',
    type: 'simple-select',
    options: [],
    fetchOptions: 'getActivityStatus',
    validation: { required: true },
    debounceDelay: 300,
  },
  {
    label: 'Description',
    name: 'description',
    type: 'text-area',
    validation: { required: true },
  },
  {
    label: 'Assigned To',
    name: 'assigned_to_id',
    type: 'searchable-select',
    options: [],
    fetchOptions: 'getEmployeeNames',
    debounceDelay: 500,
    validation: { required: true },
  },
  {
    label: 'Client/Party',
    name: 'party_id',
    type: 'searchable-select',
    options: [],
    fetchOptions: 'getPartyNames',
    debounceDelay: 500,
    validation: { required: true },
  },
  {
    label: 'Activity Type',
    name: 'activity_type_id',
    type: 'searchable-select',
    options: [],
    fetchOptions: 'getActivityTypes',
    debounceDelay: 500,
    validation: { required: true },
  },
  {
    label: 'Priority',
    name: 'activity_priority_id',
    type: 'searchable-select',
    options: [],
    fetchOptions: 'getActivityPriorities',
    debounceDelay: 500,
    validation: { required: true },
  },
  {
    label: 'Date',
    name: 'date',
    type: 'date',
    validation: { required: true },
  },
  {
    label: 'Time',
    name: 'time',
    type: 'time',
    validation: { required: true },
  },
  {
    label: 'Expected Duration (minutes)',
    name: 'expected_duration',
    type: 'number',
    validation: {
      min: 15,
      max: 480,
    },
  },
  {
    label: 'Actual Duration (minutes)',
    name: 'actual_duration',
    type: 'number',
    validation: {
      min: 15,
      max: 480,
    },
    hideInCreate: true,
  },
  {
    label: 'Outcome Notes',
    name: 'activity_outcome_id',
    options: [],
    type: 'simple-select',
    fetchOptions: 'getActivityOutcomes',
    hideInCreate: true,
    validation: { required: true },
  },
  {
    label: 'Submitted time',
    name: 'outcome_submitted_at',
    type: 'text',
    hideInCreate: true,
    readonly: true,
  },
];
