export const employeeFormConfig = [
  {
    label: 'Name',
    name: 'name',
    type: 'text',
    validation: { required: true },
  },
  {
    label: 'Employee Code',
    name: 'employee_code',
    type: 'text',
    hideInCreate: true,
    readonly: true,
  },
  {
    label: 'Email',
    name: 'email',
    type: 'text',
    validation: { required: true },
  },
  {
    label: 'Mobile',
    name: 'mobile',
    type: 'text',
    validation: { required: true },
  },
  {
    label: 'Gender',
    name: 'gender',
    type: 'simple-select',
    options: ['male', 'female', 'other'],
    validation: { required: true },
  },
  {
    label: 'Date of Birth',
    name: 'date_of_birth',
    type: 'date',
    validation: { required: true },
  },
  {
    label: 'Groups',
    name: 'employee_group_ids',
    type: 'multi-select',
    options: [],
    fetchOptions: 'getEmployeeGroup',
    debounceDelay: 500,
  },
  {
    label: 'Parties',
    name: 'party_ids',
    type: 'multi-select',
    options: [],
    fetchOptions: 'getPartyNames',
    debounceDelay: 500,
  },
  {
    label: 'Superior',
    name: 'superior_id',
    type: 'searchable-select',
    options: [],
    fetchOptions: 'getSuperiorName',
    debounceDelay: 500,
  },
  {
    label: 'Status',
    name: 'status',
    type: 'toggle',
    validation: { required: true },
  },
  {
    label: 'Account Holder Name',
    name: 'account_holder_name',
    type: 'text',
  },
  {
    label: 'Account Number',
    name: 'account_number',
    type: 'text',
  },
  {
    label: 'IFSC Code',
    name: 'ifsc_code',
    type: 'text',
  },
  {
    label: 'Bank',
    name: 'bank',
    type: 'text',
  },
  {
    label: 'Branch',
    name: 'branch',
    type: 'text',
  },
  {
    label: 'PAN Card',
    name: 'pan_card',
    type: 'text',
  },
  {
    label: 'Permanent Address',
    name: 'permanent_address',
    type: 'text-area',
    validation: { required: true },
  },
  {
    label: 'Local Address',
    name: 'local_address',
    type: 'text-area',
    validation: { required: true },
  },
];
